### ISSUE TITLE
Install command crashes if config file does not contain both dependencies and devDependencies

### ISSUE THREAD

**Issue by haakemon** [satispunk/packagelink#2]
When I define a config file with this content:
```javascript
module.exports = {
  install: {
    devDependencies: [
      'package-a'
    ],
  },
};
```
it fails with this error message: 
```
\node_modules\@satispunk\packagelink\node_modules\yargs\yargs.js:1242
      else throw err
           ^
TypeError: dependencies.push is not iterable (cannot read property Symbol(Symbol.iterator))
    at Object.handler (\node_modules\@satispunk\packagelink\dist\commands\install.js:107:18)
    at Object.runCommand (\node_modules\@satispunk\packagelink\node_modules\yargs\lib\command.js:240:40)
    at Object.parseArgs [as _parseArgs] (\node_modules\@satispunk\packagelink\node_modules\yargs\yargs.js:1154:41)
    at Object.get [as argv] (\node_modules\@satispunk\packagelink\node_modules\yargs\yargs.js:1088:21)
    at Object.<anonymous> (\node_modules\@satispunk\packagelink\dist\index.js:44:127)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
```

Workaround is to add empty dependencies array:
```javascript
module.exports = {
  install: {
    dependencies: [],
    devDependencies: [
      'package-a'
    ],
  },
};
```

I think either both dependencies and devDependencies array should be required in the schema, or default to [] if not defined. WDYT? I can submit a PR with your preference if you like :)

**Comment by satispunk** [comment]
@haakemon I don't mind having PR from you =) Will give you permissions
